# Generated by Django 4.2.1 on 2025-08-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionbatch",
            name="temperature",
            field=models.FloatField(blank=True, null=True, verbose_name="温度(℃)"),
        ),
    ]
